# Generated by Django 4.2.13 on 2025-01-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='end_date',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
