# Generated by Django 4.2.13 on 2025-01-02 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_keyresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
