# Generated by Django 4.2.13 on 2025-01-03 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_keyresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyresults', to='main_app.objective'),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyresults', to=settings.AUTH_USER_MODEL),
        ),
    ]
