# Generated by Django 4.2.13 on 2025-01-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_keyresult_objective_alter_keyresult_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('swot_categories', models.CharField(choices=[('Business', 'Business'), ('Project', 'Project'), ('Product', 'Product'), ('Team', 'Team')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Strengths', 'Strenghts'), ('Weakness', 'Weakness'), ('Opportunity', 'Opportunity'), ('Threat', 'Threat')], max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('swots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.swot')),
            ],
        ),
    ]
